// import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 500 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 500 900",
// });

const fontInter = Inter({ subsets: ["latin"], variable: "--font-sans", style: "normal", weight: ["100", "300", "400", "500", "600", "700", "800", "900"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontInter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
